version: '3'

services:
  jenkins0:
    image: jenkins:2.46.3
    ports:
      - 8080:8080
    links:
      - ldap
      - socatdockersock
    privileged: true
    volumes:
      - ./.jenkins:/var/jenkins_home

  socatdockersock:
    image: bobrik/socat:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: TCP4-LISTEN:2375,fork,reuseaddr UNIX-CONNECT:/var/run/docker.sock
 
  nginx:
    image: nginx
    volumes:
      - ./configs/jenkins.template:/etc/nginx/conf.d/jenkins.conf
    ports: 
      - 80:80
    links:
      - jenkins0

  ldap:
    image: lavcraft/slapd:test
    ports:
      - 10389:389

  juseppe:
    image: lanwen/juseppe
    ports:
      - 9030:8080
    volumes:
      - ./.juseppe:/juseppe/plugins
    environment:
      JUSEPPE_BASE_URI: "http://juseppe:8080"

