version: '3'

services:
  jenkins0:
    image: jenkins:2.46.3
    ports:
      - 8080:8080
      - 9010:9010
    links:
      - ldap
      - socatdockersock
    privileged: true
    volumes:
      - ./.jenkins0:/var/jenkins_home
      - ./.jenkins-backup:/var/jenkins_backup
    environment:
      JAVA_OPTS: "-Djava.rmi.server.hostname=localhost -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.rmi.port=9010 -Dcom.sun.management.jmxremote.port=9010 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false"

  jenkins1:
    image: jenkins:2.46.3
    ports:
      - 8090:8080
    links:
      - ldap
      - socatdockersock
    privileged: true
    volumes:
      - ./.jenkins1:/var/jenkins_home
      - ./.jenkins-backup:/var/jenkins_backup

  socatdockersock:
    image: bobrik/socat:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: TCP4-LISTEN:2375,fork,reuseaddr UNIX-CONNECT:/var/run/docker.sock

  nginx:
    image: nginx
    volumes:
      - ./configs/jenkins.template:/etc/nginx/conf.d/jenkins.conf
    ports:
      - 80:80
    links:
      - jenkins0
      - jenkins1

  bitbucket:
    image: atlassian/bitbucket-server:latest
    ports:
      - 7999:7999
      - 7990:7990
    volumes:
      - ./.bitbucket:/var/atlassian/application-data/bitbucket

  nexus:
    image: sonatype/nexus3:latest
    ports:
      - 8000:8081
      - 20000:20000
    volumes:
      - ./.nexus:/nexus-data

  ldap:
    image: lavcraft/slapd:test
    ports:
      - 10389:389

  juseppe:
    image: lanwen/juseppe
    ports:
      - 9030:8080
    volumes:
      - ./.juseppe:/juseppe/plugins
    environment:
      JUSEPPE_BASE_URI: "http://juseppe:8080"
